version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.6
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
    networks:
      - prestashop_network
    volumes:
      #      - psdata:/var/www/html
      - ./:/var/www/html:delegated
networks:
  prestashop_network:
volumes:
  psdata:
  dbdata:
